### ISSUE TITLE
Can't find system headers if invoked by a ruby script

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#114]
I ran across this issue while using flexspin from a rakefile, but even a super simple script using <code>Kernel#`</code> shows the issue:
```rb
#!/usr/bin/env ruby
`flexspin -2b -l test.c`
```
Where `test.c` is a file that references a header. Running that same command in the same directory directly from the shell works.

**Comment by totalspectrum** [comment]
I'm not able to reproduce this on my Debian Linux machine. What operating system are you using? Which version of ruby? And how is flexspin installed... are the header files in $(PATH_TO_FLEXSPIN)/../include, or are they somewhere else?

**Comment by Wuerfel21** [comment]
I'm using Windows 7 and Ruby 2.6, as installed by RubyInstaller.
Flexspin is just in a random directory I added to the %PATH% and the include directory is above that, yes.

**Comment by totalspectrum** [comment]
Are you building flexspin yourself?

The code for finding the program (and hence include files, since they're by default assumed to be relative to it) is in frontends/lexer.c, function getProgramPath. The WIN32 part is needlessly complicated, I think, and should just be reduced to the MINGW path which uses GetModuleFileNameA, and I'll check that change in soon. For the binaries I build the MINGW path is what's used.

The thing is, GetModuleFileNameA should work on WIndows to get the full file path, as long as the path fits in the buffer. The buffer is 1024 bytes; is the path name to flexspin.exe on your system longer than that? I'd be surprised if it is, and the stand-alone version wouldn't work either.

The only caveat for GetModuleFileNameA in the Microsoft docs is that it fails if the binary is loaded with LOAD_LIBRARY_AS_DATAFILE. I can't see Ruby doing that, but if it does, then there's nothing I can do to fix that :(.

**Comment by Wuerfel21** [comment]
I think the one I have installed currently is from github CI, so that'd be crosscompiled from Linux. The path to flexspin.exe is actually very short in my case: `C:\zeug\fastspin`

**Comment by Wuerfel21** [comment]
Put a printf inside `getProgramPath`. Did not come up, so I assume there's an error further up that causes it to not even call that function.

**Comment by totalspectrum** [comment]
Aha, that's the clue I needed, thank you. ruby is setting argv[0] to NULL and that was causing all the path handling stuff to be skipped. Which was silly, most platforms don't even use argv[0] any more, so I've changed that. It should be working now, please re-open if it is not.
Thanks!
