### ISSUE TITLE
Float expression evaluates to zero

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#117]
```spin
CON _CLKFREQ = 100_000_000
PUB main()
repeat
  debug(udec(round(1.0/100.0 * 4294967296.0)))
```
Title says it all. Propeller tool gives 42_949_672

**Comment by totalspectrum** [comment]
I think the title left something out, because when I type in the same program and run it on my P2 I get:

Cog0  expression = 42949672

**Comment by Wuerfel21** [comment]
No, that's really all there is to it. Simpler expressions like `round(1.0)` work fine. What are you using for float parsing? If it's sscanf or similiar, it may be Windows-specific.

**Comment by totalspectrum** [comment]
Ah, OK, the key missing piece was that it was Windows specific, or more accurate, 32 bit specific (my Linux system is 64 bits, but the Windows binaries are built with a 32 bit compiler). The float code had an "unsigned long" where it should have had "uint64_t". The fix is checked in. Thanks!

**Comment by Wuerfel21** [comment]
These are the moments that teach one to never use the long type

**Comment by Wuerfel21** [comment]
Also, what about floats that are outside the range of a 64 bit integer?

**Comment by totalspectrum** [comment]
Floats with more digits than will fit in a 64 bit integer (around 19, I think?) will probably not work properly. It's the number of digits that matter, not the size of the float -- that is, something like "1.23E+30" will work fine, even though it's too big to fit in a 64 bit number, because the "123" is what is parsed into the uint64_t, and it's then combined with the "1E+30" that's parsed separately.

**Comment by totalspectrum** [comment]
Fixed the parsing of large integers so they'll work even if more digits than will fit in 64 bits are given.
