### ISSUE TITLE
Escaping in backtick string is broken

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#191]
```spin
CON _clkfreq = 10_000_000

PUB go() | i

  debug(`TERM MyTerm SIZE 9 1 TEXTSIZE 40)
  repeat
    repeat i from 50 to 60
      debug(`MyTerm 1 'Temp = `(i)')
      waitms(500)
```
This is from the Spin2 doc and causes flexspin to segfault. It seems that the text after the escape isn't properly entered into the expression list (gets nullptr instead)

**Comment by totalspectrum** [comment]
The whole problem, I think, boiled down to a stupid typo in the lexer, which caused it to return a NULL pointer instead of the string that it was supposed to return, but the typo was hard to see :(. I've re-arranged the backtick code to try to make it clearer, fixed the typo, and added some more tests in the lexer.  It should be OK now. Thanks for catching this!
