### ISSUE TITLE
Spin2: Coginit does not check parameter count

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#204]
```spin
PUB main()
coginit(HUBEXEC_NEW,long[$18])
repeat
```
leads to
```
_main
	rdlong	arg02, #24
	mov	arg01, #48
	setq	arg03
	coginit	arg01, arg02 wc
LR__0001
	jmp	#LR__0001
_main_ret
	ret
```
arg03 is never initialized and thus leads to garbage being loaded into ptra.
If the load address is also omitted, flexspin crashes with a segmentation fault.
(Unrelatedly, the ASM optimizer seems to be having a slacker day, the `#48` could be an immediate on coginit and why is the `ret` not eliminated?)

**Comment by totalspectrum** [comment]
Thanks. I've added some sanity checks to coginit parameters. I've also fixed the coginit instruction description so the optimizer knows it does not modify its destination and hence can have a constant parameter there.

As for the "ret" instruction, it's not eliminated because it's after a label. The label itself probably shouldn't be generated, but (a) it's necessary for P1 so that call/ret work, and (b) removing it on P2 is more trouble than it's worth, because a bunch of code assumes that we can branch to that label to return. So for now I don't think I'll mess with that.

**Comment by Wuerfel21** [comment]
The PASM optimizer doesn't remove unreferenced labels? (The bytecode optimizer does)

**Comment by totalspectrum** [comment]
It removes unreferenced labels within the function. But the ones at the beginning and "end" (just before the ret) aren't part of the function, as far as the optimizer knows.

**Comment by Wuerfel21** [comment]
Also, does COGINIT really not write the destination (when it's not immediate)? How do you get the cog id then?

**Comment by totalspectrum** [comment]
Whoops! That explains why it was marked the way it was, and why no immediate was normally applied. I'll revert that change, thanks.
