### ISSUE TITLE
segmentation violation on pasm output

### ISSUE THREAD

**Issue by willis936** [totalspectrum/spin2cpp#22]
Compiling this project (Nixie_Clock_Main.spin) results in a "child killed: segmentation violation" compiler error.

https://github.com/willis936/nixieclock

**Comment by totalspectrum** [comment]
I wasn't able to reproduce your problem, but I did find that the nixieclock project exposed some bugs in the C++ conversion (calls inside static methods didn't have the self-> prefixed to them, resulting in a compiler error, and some uses of abs() were done without declaring them). I've fixed those in version 3.6.3

I also found that in order to compile directly to binary (via PASM) I had to disable fcache with the --nofcache option. This is because the compiler has no register allocation, so it exceeded the limit of registers available.

My apologies in being so slow getting back to you -- I thought I had already responded, but either my web browser or github ate my previous comment.

**Comment by cmayer68** [comment]
The (pretty amazing) VGA_HiRes_Text.spin that is one of the standard objects gives spin2cpp a bit of trouble.

spin2cpp --asm VGA_HiRes_Text.spin SEGV's.

spin2cpp --gas VGA_HiRes_Text.spin does not produce a compilable file, as the
   assembly overflows the 9 bit offsets.  this is probably because org does not work on gas
   like it does on pasm.

spin2cpp --gas --dat VGA_HiRes_Text.spin hangs in an infamous loop.

**Comment by willis936** [comment]
I have been trying to find the cause of this issue.  I have been able to reproduce in on every system I have tried so I'm not sure what it could be.  It happens on every combination of these settings: make binary, code memory location, data memory location, and common subexpression optimizations.  This only happens when trying to convert "Nixie_Clock_Main.spin".

A different error occurs when trying to convert "string.float.spin": "child process exited abnormally".
