### ISSUE TITLE
spin2 files ftbfs when _xtlfreq is used

### ISSUE THREAD

**Issue by avsa242** [totalspectrum/spin2cpp#269]
Hey Eric, there's an issue when building spin2 files if `_xtlfreq` is used (presumably `_xinfreq` as well; not tried).
The compiler bombs out with `error: _xinfreq and _xtlfreq are redundant with _clkmode`.
_(just FYI, in my spin2 source, I'm using `_clkfreq` specifically, not `_clkmode`)_

This looks to be a side effect of _clkmode behavior changes for C introduced in ce90e8a56b722c0e7701e14eae84ac79df9c05e5 (the previous commit builds spin2 code fine with the crystal freq specified).
At least for the Edge and Eval boards, removing the `_xtlfreq` directive as a workaround doesn't seem to affect operation; the correct xtal freq must be getting selected by default, as code still runs.

Cheers

**Comment by totalspectrum** [comment]
Thanks, Jesse. The xtlfreq defaults to the one used in Edge and Eval boards, so it isn't necessary to specify for those. For others it's useful to specify. For now I've removed the error, since specifying both _xtlfreq and _clkmode isn't necessarily wrong, just unnecessary (and now _clkmode gets calculated automatically for high level languages, so it ends up always specified in the assembly output from HLL).
