### ISSUE TITLE
Using getcnt() builtin function for fastSpin BASIC gives compile error: Expected integer type for parameter of operator

### ISSUE THREAD

**Issue by dgately** [totalspectrum/spin2cpp#31]
The following .bas program fails to build in fast spin:
`rem simple program to toggle a pin
const pin = 16

let mscycles = clkfreq / 1000
direction(pin) = output

do
  output(pin) = not output(pin)
  pausems 1000
loop

sub pausems(ms)
    waitcnt(getcnt() + ms * mscycles)
end sub`

`$ fastspin fsTest.bas 
Propeller Spin/PASM Compiler 'FastSpin' (c) 2011-2018 Total Spectrum Software Inc.
Version 3.9.5-beta Compiled on: Oct  2 2018
fsTest.bas
fsTest.bas(15) error: Expected integer type for parameter of operator`

This fails for P1 and P2 ("-2" option)... 

For P1, getcnt() can be replaced with "cnt", similar to .spin, but that fails with the "-2" option...

`$ fastspin fsTest.bas 
Propeller Spin/PASM Compiler 'FastSpin' (c) 2011-2018 Total Spectrum Software Inc.
Version 3.9.5-beta Compiled on: Oct  2 2018
fsTest.bas
fsTest.pasm
Done.
Program size is 572 bytes`
`$ fastspin -2 fsTest.bas 
Propeller Spin/PASM Compiler 'FastSpin' (c) 2011-2018 Total Spectrum Software Inc.
Version 3.9.5-beta Compiled on: Oct  2 2018
fsTest.bas
fsTest.bas(16) error: Expected integer type for parameter of operator`

`rem simple program to toggle a pin
const pin = 16
let mscycles = clkfreq / 1000
direction(pin) = output

do
  output(pin) = not output(pin)
  pausems 1000
loop

sub pausems(ms)
REM    waitcnt(getcnt() + ms * mscycles)
    waitcnt(cnt + ms * mscycles)
end sub`

**Comment by totalspectrum** [comment]
Thanks for the bug report! As a work-around for now the arithmetic operators accept "generic" types (type ANY), which is generally the type assigned to Spin functions like getcnt(). The long term fix is probably to re-write all the internal functions in BASIC so that they have proper types, but that will take a little while. Arguably it is probably useful to allow type ANY to participate in arithmetic, although it probably deserves a warning.
