### ISSUE TITLE
Bad STRCOPY implementation

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#313]
The new `STRCOPY`/`__builtin_strncpy` function is buggy, it does not ensure that the resulting buffer is zero-terminated.
Should work:
```
pri __builtin_strncpy(dst, src, maxn) : r=@byte | n
  n := __builtin_strlen(src) <# maxn
  bytemove(dst, src, n)
  byte[dst][n] := 0
  return dst
```

**Comment by totalspectrum** [comment]
Aargh, yes, of course. Thanks for catching this. It's fixed in github now.

**Comment by Wuerfel21** [comment]
You didn't push it yet. Anyways, even my impl above is arguably a bit problematic. I think having the strlen in there is kinda bad, since that will scan to the end of src regardless of the limit.

**Comment by Wuerfel21** [comment]
Oh wait, the strlen version was only in the bytecode file, oop. Fine there probably, since the strlen opcode is so fast by comparsion to everything else going on.

Eitherhow, I think now the strlen version is in common, which, uhhhh.

Loop version I guess: 
```spin
pri __builtin_strncpy(dst, src, n) : r=@byte | c
  r := dst
  repeat n
    ifnot byte[dst++] := byte[src++]
      return
  byte[dst] := 0
```
Chip's interpreter uses FIFO.

**Comment by Wuerfel21** [comment]
FIFO version
```spin
pri __builtin_strncpy(dst, src, n) : r=@byte
  r := dst
  org
    mov ptrb,dst
    rdfast #0,src
    rep @.loop, n
    rfbyte n wz
    if_z jmp #.loop
    wrbyte n,ptrb++
    .loop
    wrbyte #0,ptrb++
  end
```

**Comment by totalspectrum** [comment]
Calling strlen isn't really a problem, it's going to terminate eventually (there are surely some 0's somewhere in memory!). I've gotten rid of the assembly-only code and just put a single copy in sys/common.spin because it simplifies maintainance. The FIFO version, for example, will be faster but requires FCACHE to be active (cannot run from hub). I'm not too worried if STRCOPY is a bit slower than optimal, it's a new feature and I doubt it will be used much.
Thanks!
