### ISSUE TITLE
spin: When building to native code, a descending repeat loop continues past its target

### ISSUE THREAD

**Issue by avsa242** [totalspectrum/spin2cpp#315]
Good evening!

I found an issue with descending `repeat` loops if the `step` delta is set other than 1. It seems it goes past its target value and keeps going.

In the following example,

```spin
obj ser: "FullDuplexSerial"

pub main | x

    ser.start(31, 30, 0, 115200)
    waitcnt(cnt+clkfreq/10)

    repeat x from 31 to 1 step 2     ' bad: keeps going below 1
'    repeat x from 31 to 1 step 1    ' OK
        ser.dec(x)
        ser.str(string(10, 13))
```
x reaches 1, but keeps going past it, ever negative.
If the step delta is set to 1, all is good.
If building to bytecode, all is good.

The equivalent spin2 (NuCode as well as native code) both seem to be affected by this, too.
I started with a 5.9.18-beta, and then tried 5.9.20 (e5e36d64a609fefe61b94985b17dbb7fb6f8ffad) - same results.

Cheers

**Comment by totalspectrum** [comment]
Thank you for the bug report! It's actually even stranger than you suspected: the loop works if you count down to 3 or to 0. It turns out the bug is related to whether the final test will be signed or unsigned, and if the final value is > 0 but the final value - step is < 0 then the calculation was wrong.

It should be fixed in the github source code now.

(In the case of P1 bytecode output this whole optimization was skipped, which is why that one worked.)

Thanks!

**Comment by Wuerfel21** [comment]
The check for step!=1 is probably less than ideal. step < end may be more ideal.

**Comment by totalspectrum** [comment]
I don't think step < end would work. toi + step > 0 probably would. But at least what's there now works
