### ISSUE TITLE
Source code indentation inconsistencies

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#325]
Some files are mostly 4-space, some tend towards 2-space, sometimes there are tabs?

Should this be harmonized at some point? And to what standard (I vote 4-space because idk that's just what I use)

**Comment by totalspectrum** [comment]
I've reformatted a bunch of code using the default format style of astyle (https://astyle.sourceforge.net/) and it seems to have come out OK. It uses 4 space indentation and reasonably sane conventions for brackets. I haven't touched the bytecode backend because you wrote most of that. But I think overall things are more sane now.

**Comment by Wuerfel21** [comment]
Yea, seems to have done a good job, except that compacted cases like in `ApplyConditionAfter` are now a bit of a mess. (Also, is it just me or is the WRC/WRZ section in that function missing `change=1` statements?)
