### ISSUE TITLE
fastspin fails to compile PASM with character arithmetic involving non-ASCII characters

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#33]
lines like
```
if_c            cmp     data,#"ß"-$40   wz
```
result in this output: 
```
D:/[...]/germanKeyboard.spin(288) warning: only first element of string is used
D:/[...]/germanKeyboard.spin(288) error: Source operand too big for cmp
```
this type of expression works fine for regular alphanumeric characters

**Comment by totalspectrum** [comment]
I don't think that's a bug. The string "ß" is encoded in UTF-8 as two bytes, $C3 and $9F, so fastspin's warning about only the first element of the string being used is because the string has two bytes in it. I'm not sure how your input data is achieved, but it may be that you were hoping to compare the "data" variable to the Unicode value for "ß". You'll probably have to use explicit hex values for that.

**Comment by Wuerfel21** [comment]
I'd say it's a bug, since this works fine in both BST and Prop tool

**Comment by totalspectrum** [comment]
Hmmm, interesting point. I guess BST and Prop tool default to a different encoding for strings (probably Latin-1). Ugh. I'd really like to use UTF-8 because it's a more widely used standard, and supports more languages.

Have you tried using a character outside of the Unicode 00-FF range in that expression?

**Comment by totalspectrum** [comment]
I guess I could use Latin-1 for .spin files and UTF-8 for everything else. That makes interoperation between languages harder though.

**Comment by drawkula** [comment]
> I guess I could use Latin-1 for .spin files and UTF-8 for everything else.

Please don't.

Characters outside the 0...127 range always are a problem.
I'd put this into a FAQ topic and stay with UTF-8 everywhere.

**Comment by Wuerfel21** [comment]
Spin/P1 (not sure about Spin2 / P2) in general have their own codepage based on Latin-1, plus a bunch of random graphic characters. This codepage is used by proptool, parallax serial terminal and is also what the ROM font covers. Proptool saves files containing extended characters as unicode, but translates them to its custom codepage when compiling.
For example, the € is $20AC in unicode and $A4 in Spin codepage
![image](https://user-images.githubusercontent.com/6944842/53906936-648a7b00-404c-11e9-83e7-5fd3b3a2e452.png)

**Comment by drawkula** [comment]
Different editors may use different codepages. Only ASCII is safe to use. I'd use constants with nice names (PCP_SZ = $DF, PCP_EURO = $A4, ...) instead of the character constants in this cases to make my source code robust.

Btw: OpenSpin dislikes the UTF-8 "ß" too and OpenSpin the Propellertool compiler successor...

**Comment by Wuerfel21** [comment]
Spin files are usually UTF-16 (little endian, with BOM), tried that? I can't download openspin myself right now, github's donwload servers are timing out

**Comment by drawkula** [comment]
Living in the Unix parrallel universe I want ASCII UTF-8 and I strongly dislike the UTF-16 coding.

**Comment by totalspectrum** [comment]
Actually this particular case could probably be handled specially: if the compiler detects use of a multi-byte string in a context where only a single character is expected, and if that multi-byte string is a UTF-8 sequence representing a single Unicode character, the compiler could convert the string to the Unicode codepoint. Does that sound like a reasonable compromise? It would fix @Wuerfel21 's example, at least, and it would leave data strings as UTF-8.

**Comment by totalspectrum** [comment]
As of 3.9.23 fastspin checks for multi-byte UTF-8 sequences that represent a single Unicode character, and uses that character when a single integer is expected.
