### ISSUE TITLE
Conditional assembly

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#363]
As proposed a while ago, it would be useful to have proper conditional assembly based on constant expressions, especially given the constant override feature.

Example:
```spin
CON
FOO = 123

DAT

if FOO < 0
   ' nothing
elseif FOO > 511
    mov pa,##FOO
else
    mov pa,#FOO
end
```

IF, ELSE, END, etc are already reserved words for DAT sections in PNut, so no conflict possiblity, I think.

**Comment by totalspectrum** [comment]
Yes, this would be nice. But there's probably no point in doing it if Chip doesn't agree :(.

**Comment by Wuerfel21** [comment]
It's not like he disagreed :)

It's not terribly invasive or nuanced and I arguably need it yesterday.

**Comment by totalspectrum** [comment]
END is a problem, it isn't available in inline assembly :(. Maybe scoping rules could get around this. For now, especially since Chip isn't on board yet, I've gone with using reserved words starting with `%`: `%if`, `%elseif`, `%else`, and `%endif`. It's checked in now, although I haven't tried it in inline asm yet.

**Comment by Wuerfel21** [comment]
Also the example in the documentation has `%end` instead of `%endif`
