### ISSUE TITLE
Enabling listing changes binary output

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#383]
Compiling usb_to_vga.spin2 with -l and without -l produces a different binary. The -l enabled binary is broken, but I've had inexplicable breakage without it, too. I think it's something to do with the conditional ASM `else`?

[list_bug.zip](https://github.com/totalspectrum/spin2cpp/files/11365431/list_bug.zip)

Also, the built-in ZIP tool failed. Will another open issue for that.

**Comment by totalspectrum** [comment]
Oddly enough this doesn't seem to be a problem in the conditional assembly. It's the peephole optimizer -- when -l is enabled some comments are inserted into the generated IR, and this causes the peephole optimizer to stop working because the patterns don't match (comments are not ignored). The generated code should be OK in either case, but obviously it would be nice to have the peephole optimizer run when -l is enabled.

**Comment by Wuerfel21** [comment]
Hmm, but that doesn't explain why everrything turns into 44 44 44 with -l. I guess if the peephole issue is fixed we would see any further discrepancy

**Comment by totalspectrum** [comment]
There was another problem too, namely that if a file didn't end in a newline then its last comment line (intended for the listing file) also didn't have a newline, which caused it to eat the next line of assembly -- in this case, some of the data. That is fixed now, as is the peephole problem.
