### ISSUE TITLE
Add `-o` option for specifying output filename

### ISSUE THREAD

**Issue by DavidZemon** [totalspectrum/spin2cpp#4]
Can you add an option for specifying an output filename?

**Comment by totalspectrum** [comment]
There is a -o option for specifying the output filename, but it only applies to binary outputs (.elf and .binary). For source output the input file name is always used, because we have to trace through all of the OBJ includes, so there's not one single output file.

**Comment by DavidZemon** [comment]
I'm thinking specifically for the `--dat` option. I'm attempting to integrate spin2cpp into PropWare for easy integration of Spin in the build system, and I had to write some ugly code wrapping spin2cpp because the output path/name couldn't be specified.

**Comment by totalspectrum** [comment]
-o actually applied to .dat output as well -- I forgot to enumerate that.

There was an issue that any extension specified in -o was overwritten by .dat (e.g. if you said "--dat -o foo.bin" the output file would actually be called "foo.dat". I think that should be fixed now.

Thanks,
Eric

**Comment by DavidZemon** [comment]
Oh, wonderful! Thank you!

**Comment by DavidZemon** [comment]
Well... I'm trying to add support for Spin2Cpp's C++ output into PropWare. Now I could really use a `-o` option for Spin -> C++ files. Could it support an output directory?

**Comment by totalspectrum** [comment]
Hmmm, I hadn't realized that -o didn't work for the .cpp output. It shouldn't be too hard to support, but I think there will be limitations. The C++ code and header are almost certainly going to have to have the same base name. Will that be OK for you? Do you need to specify flexible extensions for the output, or is always using .cpp and .h going to work?

**Comment by totalspectrum** [comment]
I've changed it so that -o somedir/foo.cpp will put the source code for the top level object into somedir/foo.cpp, but there are still a few problems:

(1) If the file is not called "foo.spin" then the #include will be wrong (it will still use the original spin file name to create the #include).
(2) Only the C++ code for the top level object is placed in that directory; the others still go in the current directory.

So not as useful as it could be yet, but perhaps it's better than nothing.

On the other hand the -o option does put ELF output files into the right place, so if you go directly from .spin to .o the .o's will be OK. You will clutter up the current directory with .cpp and .h files though, sadly.

**Comment by DavidZemon** [comment]
Ah, I was thinking `-o` would just take an output directory in this case. Then it would dump all files into that directory.

I was actually able to get PropWare working very nicely with Spin2Cpp once I found the option which provides names of generated files. I combine each of those lines with `${CMAKE_CURRENT_BINARY_DIR}` and then I know what files need to be compiled into the executable (and added to the `clean` target). Then I run spin2cpp in `${CMAKE_CURRENT_BINARY_DIR}` and all is good. But it'd be great if I didn't have to run spin2cpp in a specific directory and could instead provide `${CMAKE_CURRENT_BINARY_DIR}` to `-o`.

**Comment by totalspectrum** [comment]
Now if -o is given and there's a compilation step (--elf or --binary) then all the generated files are placed in the same directory as the final output specified by -o. I hope that'll do the trick.
