### ISSUE TITLE
Called spin2 method doesn't return

### ISSUE THREAD

**Issue by avsa242** [totalspectrum/spin2cpp#52]
[HexToStr-Test.zip](https://github.com/totalspectrum/spin2cpp/files/4365610/HexToStr-Test.zip)
In the attached test (top-level object is HexToStr-Test.spin2), the called method HexToStr should return the address of a VAR and the program should print out the number given in hex, but it never seems to return and the program hangs there. However, if some debugging output is added to the method (anywhere), the method then functions properly and returns.
I don't know enough PASM to fully understand the produced p2asm, but without the printf, there's no code generated that looks stack-related (push, pop), whereas if the printf is included, there's this code (among a few other additional lines) produced at the beginning of the subroutine:

`
     mov     COUNT_, #7
`
`
     calla   #pushregs_
`

and at the end:

`
calla   #popregs_
`

BTW the code is actually an excerpt of a child object in the archive, string.integer.spin2, which is a port of Parallax's original Simple_Numbers.spin from the Propeller Tool lib.

Any ideas? Are there better spin2-specific ways of doing anything that stand out to you?
Hope you're feeling better!

**Comment by totalspectrum** [comment]
Thanks for the bug report! The underlying bug was that LOOKUP/LOOKDOWN expand internally into function calls, but the compiler didn't save registers (the functions containing them could still be considered leaf functions). That should be fixed now.

The HexToStr-Test.spin2 program also has a typo ("byte[nstr][idx]" instead of "byte[@nstr][idx]" or better just "nstr[idx]"). This isn't there in the original string.integer.spin2.
